[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.38.0",
    "pathlib>=1.0.1",
    "requests>=2.32.5",
    "rich>=14.1.0",
]
